name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Build Script
      run: sh ./build.sh

    - name: Create and Push Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        TAG_NAME="release-$(date +%Y%m%d%H%M%S)-${GITHUB_SHA:0:8}"
        git tag $TAG_NAME $GITHUB_SHA
        git push origin $TAG_NAME

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: $TAG_NAME
        release_name: Release $TAG_NAME
        draft: false

    - name: Upload AppImage to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./*.AppImage
        asset_content_type: application/octet-stream
